server:
  port: 8087

spring:
  application:
    name: mall-review
  datasource:
    url: jdbc:mysql://localhost:3306/rjjg?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: liujian3732028
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        service: mall-review
