server:
  port: 8082

spring:
  application:
    name: mall-product
  datasource:
    url: jdbc:mysql://localhost:3306/rjjg?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: liujian3732028
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        service: mall-product

seata:
  enabled: true
  application-id: mall-product
  tx-service-group: mall-product-group
  service:
    vgroup-mapping:
      mall-product-group: default
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: localhost:8848
      group: SEATA_GROUP
