server:
  port: 8085

spring:
  application:
    name: mall-order
  datasource:
    url: jdbc:mysql://localhost:3306/rjjg?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: root
    password: liujian3732028
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        service: mall-order

seata:
  enabled: true
  application-id: mall-order
  tx-service-group: mall-order-group
  service:
    vgroup-mapping:
      mall-order-group: default
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: localhost:8848
      group: SEATA_GROUP

mall:
  product:
    direct-url: http://127.0.0.1:8082